# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=32, null=True)),
                ('text2', models.CharField(max_length=32, null=True)),
                ('text3', models.CharField(max_length=32, null=True)),
                ('text4', models.CharField(max_length=32, null=True)),
                ('text5', models.CharField(max_length=32, null=True)),
                ('text6', models.CharField(max_length=32, null=True)),
                ('text7', models.CharField(max_length=32, null=True)),
                ('text8', models.CharField(max_length=32, null=True)),
                ('text9', models.CharField(max_length=32, null=True)),
                ('text10', models.CharField(max_length=32, null=True)),
                ('text11', models.CharField(max_length=32, null=True)),
                ('text12', models.CharField(max_length=32, null=True)),
                ('text13', models.CharField(max_length=32, null=True)),
                ('text14', models.CharField(max_length=32, null=True)),
                ('text15', models.CharField(max_length=32, null=True)),
                ('text16', models.CharField(max_length=32, null=True)),
                ('text17', models.CharField(max_length=32, null=True)),
                ('text18', models.CharField(max_length=32, null=True)),
                ('text19', models.CharField(max_length=32, null=True)),
                ('text20', models.CharField(max_length=32, null=True)),
                ('text21', models.CharField(max_length=32, null=True)),
                ('text22', models.CharField(max_length=32, null=True)),
                ('text23', models.CharField(max_length=32, null=True)),
                ('text24', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
