# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0003_auto_20180329_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text25',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text26',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text27',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text28',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
