# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0003_auto_20180417_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userlimitid',
            field=models.IntegerField(blank=True, choices=[(0, '超级用户'), (1, '普通员工'), (2, '编外人员')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='userId',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='codetime.Person'),
        ),
    ]
