# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0004_auto_20180417_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='text4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='text8',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
