# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0004_auto_20180331_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text29',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text30',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
