# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0008_auto_20180421_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text24',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='text3',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='text6',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='text7',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='text9',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
