# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0011_remove_product_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userId',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='codetime.Person'),
        ),
    ]
