# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0012_product_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userId',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
