# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0013_auto_20180624_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retention_samples',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
