# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0017_auto_20200419_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='template_img_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
