# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0021_uploadimage_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
