# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codetime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('userlimitid', models.IntegerField(choices=[(0, '超级用户'), (1, '普通员工'), (2, '编外人员')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=32, null=True)),
                ('text2', models.CharField(blank=True, default='', max_length=32)),
                ('text3', models.CharField(max_length=32, null=True)),
                ('text4', models.CharField(max_length=32, null=True)),
                ('text5', models.CharField(max_length=32, null=True)),
                ('text6', models.CharField(max_length=32, null=True)),
                ('text7', models.CharField(max_length=32, null=True)),
                ('text8', models.CharField(max_length=32, null=True)),
                ('text9', models.CharField(max_length=32, null=True)),
                ('text10', models.CharField(blank=True, default='', max_length=32)),
                ('text11', models.CharField(blank=True, default='', max_length=32)),
                ('text12', models.CharField(blank=True, default='', max_length=32)),
                ('text13', models.CharField(blank=True, default='', max_length=32)),
                ('text14', models.CharField(blank=True, default='', max_length=32)),
                ('text15', models.CharField(blank=True, default='', max_length=32)),
                ('text16', models.CharField(blank=True, default='', max_length=32)),
                ('text17', models.CharField(blank=True, default='', max_length=32)),
                ('text18', models.CharField(blank=True, default='', max_length=32)),
                ('text19', models.CharField(blank=True, default='', max_length=32)),
                ('text20', models.CharField(blank=True, default='', max_length=32)),
                ('text21', models.CharField(blank=True, default='', max_length=32)),
                ('text22', models.CharField(blank=True, default='', max_length=32)),
                ('text23', models.CharField(max_length=32, null=True)),
                ('text24', models.CharField(max_length=32, null=True)),
                ('text25', models.CharField(blank=True, default='', max_length=32)),
                ('text26', models.CharField(blank=True, default='', max_length=32)),
                ('text27', models.CharField(blank=True, default='', max_length=32)),
                ('text28', models.CharField(blank=True, default='', max_length=32)),
                ('text29', models.CharField(blank=True, default='', max_length=32)),
                ('text30', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('shipments', models.BooleanField(default=False)),
                ('knot', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codetime.Person')),
            ],
        ),
    ]
