# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0002_person_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
