# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0007_auto_20180419_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
