# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0009_auto_20180504_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text31',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='text3',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
