# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0018_auto_20200419_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='userId',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
