# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetime', '0019_uploadimage_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='template_img_md5',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
